# Copyright Â© 2023-2026 ValidMind Inc. All rights reserved.
# See the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial

format:
  html:
    page-layout: full
    navbar: false
    code-tools: true
    repo-actions: false
    include-in-header: 
      - environments/heap-staging.html
execute: 
  enabled: true
  freeze: auto
