website:
  navbar:
    right:
      - text: "Log In"
        href:  https://app.prod.validmind.ai/

format:
  html:
    include-in-header: 
      - environments/datadog-production.html
      - zendesk-chat.html