format:
  html:
    page-layout: full
    navbar: false
    code-tools: true
    repo-actions: false
    include-in-header: 
      - environments/datadog-production.html
execute: 
  enabled: true
  freeze: auto
