website:
  navbar:
    right:
      - text: "Log In"
        href:  https://app.staging.validmind.ai/

format:
  html:
    include-in-header: 
      - environments/datadog-staging.html
      - zendesk-chat.html