# Copyright Â© 2023-2026 ValidMind Inc. All rights reserved.
# Refer to the LICENSE file in the root of this repository for details.
# SPDX-License-Identifier: AGPL-3.0 AND ValidMind Commercial

website:
  navbar:
    right:
      - text: "Log In"
        href:  https://app.staging.validmind.ai/

format:
  html:
    include-in-header: 
      - environments/datadog-staging.html
      - zendesk-chat.html
      - environments/noindex.html